language: java
install: mvn clean install

notifications:
  email:
    recipients:
      - prajesh.ananthan@outlook.com
    on_success: always # default: change
    on_failure: always # default: always

addons:
  coverity_scan:
    project:
      name: "prajesh.ananthan/e-commerce"
      description: "Build submitted via Travis CI"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master